"""Hardware allocation adapter; original frozen training/evaluation engines unchanged."""
import argparse
import fcntl
import json
import os
from pathlib import Path
import shlex
import subprocess
import time
from src.provenance import save_json,sha256

ROOT=Path('results/topology_confirmation_v2')
AMENDMENT=ROOT/'hardware_amendment.json'
KEY=str(Path.home()/'.ssh/flygpt_mac_mini_ed25519')
HOST='alex@100.98.214.41'
SSH=['ssh','-i',KEY,'-o','IdentitiesOnly=yes','-o','BatchMode=yes','-o','ConnectTimeout=15',HOST]
REMOTE='/Users/alex/flygpt'

def read(p):return json.loads(Path(p).read_text())
def remote(command):
    return subprocess.run([*SSH,command],check=True,capture_output=True,text=True).stdout
def fetch(source,dest):
    dest=Path(dest);dest.parent.mkdir(parents=True,exist_ok=True)
    # Paths generated by our own scripts, never arbitrary shell fragments.
    with dest.with_suffix(dest.suffix+'.partial').open('wb') as stream:
        subprocess.run([*SSH,'cat '+shlex.quote(source)],stdout=stream,check=True)
    dest.with_suffix(dest.suffix+'.partial').replace(dest)

def verify_remote_inputs():
    for p,h in read(ROOT/'frozen_plan.json')['inputs'].items():
        mapped=p
        prefix='/Users/alex/Desktop/flygpt_v01/'
        if p.startswith(prefix):mapped=p[len(prefix):]
        if sha256(mapped)!=h:raise RuntimeError(f'Frozen input mismatch: {p}')
    amendment=read(AMENDMENT)
    if sha256(__file__)!=amendment['adapter_sha256']:raise RuntimeError('Dispatch adapter changed')

def worker():
    from scripts import run_compiler_v1 as v
    v.ROOT=ROOT;v.refresh=lambda:None
    lock=(ROOT/'remote_worker.lock').open('w');fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
    awake=subprocess.Popen(['caffeinate','-is','-w',str(os.getpid())])
    try:
        verify_remote_inputs();plans=read(ROOT/'frozen_plan.json')['pairs']
        for seed in read(AMENDMENT)['m4_seeds']:
            for condition,p in plans[str(seed)].items():
                verify_remote_inputs()
                save_json(ROOT/'remote_status.json',dict(stage='training',seed=seed,condition=condition,pid=os.getpid()))
                checkpoint=v.train(p,'scripts.g2c_engine')
                job=Path(read(p)['job_dir'])
                save_json(job/'remote_receipt.json',dict(seed=seed,condition=condition,checkpoint=checkpoint,
                    checkpoint_sha256=sha256(checkpoint),progress_sha256=sha256(job/'progress.json'),
                    spec_sha256=sha256(p),hardware='Apple M4, 16 GiB; Python 3.12.12; frozen package versions',
                    amendment_sha256=sha256(AMENDMENT),final_test_opened=False))
        save_json(ROOT/'remote_status.json',dict(stage='training_complete',final_test_opened=False))
    except BaseException as exc:
        import traceback
        save_json(ROOT/'remote_failure.json',dict(error=repr(exc),traceback=traceback.format_exc()));raise
    finally:awake.terminate()

def coordinator():
    from scripts import run_topology_confirmation_v2 as c
    from scripts import run_compiler_v1 as v
    amendment=read(AMENDMENT)
    if sha256(__file__)!=amendment['adapter_sha256']:raise RuntimeError('Dispatch adapter changed')
    # Preserve the in-flight M1 run through scheduler-only handoff.
    pid=amendment['retained_m1_child_pid']
    while True:
        state=subprocess.run(['ps','-p',str(pid),'-o','stat='],capture_output=True,text=True).stdout.strip()
        if not state or state.startswith('Z'):break
        time.sleep(20)
    original_train=v.train
    def train(path,engine):
        spec=read(path)
        if spec['seed'] not in amendment['m4_seeds']:return original_train(path,engine)
        job=Path(spec['job_dir']);receipt_path=job/'remote_receipt.json'
        while not receipt_path.exists():
            # Remote jobs are already running in parallel; never start duplicates here.
            failure=remote('test ! -f '+shlex.quote(REMOTE+'/'+str(ROOT/'remote_failure.json'))+' || cat '+shlex.quote(REMOTE+'/'+str(ROOT/'remote_failure.json')))
            if failure.strip():raise RuntimeError('M4 worker failed: '+failure)
            source=REMOTE+'/'+str(receipt_path)
            present=remote('test ! -f '+shlex.quote(source)+' || echo ready').strip()
            if present:
                fetch(source,receipt_path);break
            time.sleep(20)
        receipt=read(receipt_path)
        assert receipt['spec_sha256']==sha256(path) and receipt['amendment_sha256']==sha256(AMENDMENT)
        for name in ['progress.json','engine_source.py','train.log']:
            fetch(REMOTE+'/'+str(job/name),job/name)
        assert sha256(job/'progress.json')==receipt['progress_sha256']
        checkpoint=Path('artifacts/m4_import')/f"seed_{spec['seed']}"/(spec['condition']+'.pt')
        if not checkpoint.exists():fetch(receipt['checkpoint'],checkpoint)
        if sha256(checkpoint)!=receipt['checkpoint_sha256']:raise RuntimeError('Transferred checkpoint hash mismatch')
        assert read(job/'progress.json')['step']==1024
        return str(checkpoint)
    v.train=train
    original_freeze=c.freeze
    def freeze(path,value):
        if str(path)==str(ROOT/'unlock.json'):
            value={**value,'inputs':{**value['inputs'],str(AMENDMENT):sha256(AMENDMENT),str(Path(__file__)):sha256(__file__)}}
        return original_freeze(path,value)
    c.freeze=freeze
    original_analysis=c.analysis
    def analysis(real,rewired):
        result=original_analysis(real,rewired)
        result['hardware_assignment']={'M1':amendment['m1_seeds'],'M4':amendment['m4_seeds']}
        result['hardware_scope']='Paired contrasts within machines; five-seed aggregate spans two hardware blocks. Allocation based on timing, before new final tests.'
        return result
    c.analysis=analysis
    c.run()
    report=Path('TOPOLOGY_CONFIRMATION_REPORT.md')
    if report.exists():
        with report.open('a') as f:f.write('\nHardware amendment: seeds 100–101 trained on M1; 102–104 on M4. Both conditions within each pair used the same machine. Reported effect is across these two hardware blocks; no hardware-specific significance claim. All final evaluation ran on the primary M1 after every checkpoint completed.\n')
        c.preserve('Topology confirmation: record distributed hardware scope in final report')

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--worker',action='store_true');a=p.parse_args()
    if a.worker:worker()
    else:coordinator()
